### ISSUE TITLE
README.md updates

### ISSUE THREAD

**Issue by ryan-miller** [ryan-miller/pyrunplan#3]
It would be great if the README would link to the **Usage** section when Usage is mentioned. Also, the **Acknowledgements** section is a repeat of the **Options** section. We can remove that.

**Comment by Mount-Blanc** [comment]
Hello, I would like to work on this issue.

**Comment by ryan-miller** [comment]
@Mount-Blanc go for it. Thanks.

**Comment by ryan-miller** [comment]
Thanks @Mount-Blanc!
